### ISSUE TITLE
Improve permissions system

### ISSUE THREAD

**Issue by Zoddo** [ErnadoO/qte#1]
When no forums/groups are selected in attribute permissions, assume that all forums/groups are allowed to use the attribute.

**Comment by ErnadoO** [comment]
I think is a wrong idea.
Ok for no forums selected, but if no groups selected assume that all groups are allowed to use the attribute, you can no longer allow an attribute to the topic author only (which is actually possible if you don't select any group and check the "Allow the topic author to use that attribute in the selected forums" option)
