### ISSUE TITLE
I have problem with qte topic

### ISSUE THREAD

**Issue by Scorpions95** [ErnadoO/qte#22]
Hi here 
i made a video about my problem wiyh ur extension qte topic here is the video
https://youtu.be/_P0afo5JVeg

**Comment by ErnadoO** [comment]
Hi

3 mistakes:

1. support is on phpbb.com (https://www.phpbb.com/community/viewtopic.php?f=456&t=2218556)

2. You use the wrong extension, the good one is ernadoo/qte, not abdev/qte

2. your board is 3.3.2 but:
![LOL](https://image.noelshack.com/fichiers/2018/31/7/1533481405-capture2.png)

**Comment by Scorpions95** [comment]
![screenshot 2018-08-05 18 39 46](https://user-images.githubusercontent.com/24534657/43687511-f809d4fe-98de-11e8-94a3-79445ccb4f2b.png)
i also have this one @ErnadoO

**Comment by ErnadoO** [comment]
As i said, it’s the good one

**Comment by Scorpions95** [comment]
@ErnadoO but i want to use only admins ,but this is only avalible if i remove myself from registered users
as you can see on this video https://www.youtube.com/watch?v=EjbHzx7kfrE&feature=youtu.be
and this video https://www.youtube.com/watch?v=2Lfsb6wqfMA&feature=youtu.be

**Comment by Scorpions95** [comment]
in ur version of qte how can i create new topic attribute?

**Comment by ErnadoO** [comment]
You show yoursel your mistake on your first video: permissions for registered users are set on NEVER, so, indeed, if you (admin) are in this group, you lose your right of use attribute.
Change never to no.

> in ur version of qte how can i create new topic attribute?

Same as before, posting tab in ACP

**Comment by Scorpions95** [comment]
![screenshot 2018-08-05 20 02 17](https://user-images.githubusercontent.com/24534657/43688059-83b7fe58-98ea-11e8-90c0-baa9c9020a2a.png)
um where in ACP?
@ErnadoO 
![screenshot 2018-08-05 20 03 26](https://user-images.githubusercontent.com/24534657/43688073-bb5aa478-98ea-11e8-8b8f-edf8487c7bc7.png)

**Comment by ErnadoO** [comment]
Please, read what i wrote : In POSTING tab, not FORUMS tab !

**Comment by Scorpions95** [comment]
@ErnadoO 
![screenshot 2018-08-05 21 26 16](https://user-images.githubusercontent.com/24534657/43688697-3a43cd22-98f6-11e8-9b65-1eb7b201ecf1.png)
well..?

**Comment by Scorpions95** [comment]
how can i fix this?
https://youtu.be/wEukGNHYT2U
well i you want u can make [url=http://test.kefcheto.eu/ucp.php?mode=register]register[/url] in my [url=http://test.kefcheto.eu]test board[/url] i'll gave u a admin account to see what actually is the problem

**Comment by ErnadoO** [comment]
...

And again, and again, and again, you use the WRONG extension !

The good one is ernadoo/qte, NOT abdev/qte !!!

**Comment by Scorpions95** [comment]
@ErnadoO 
After some hour needed option is apear in POSTING TAB
but i habe same problem as before
https://github.com/ErnadoO/qte/issues/22#issuecomment-410532373
but this time i set the permission on NO but again can't put attribute on registered users when post new topic as i who in my [video](https://youtu.be/G3t7ne0jj58)

**Comment by ErnadoO** [comment]
It's not the same problem:
Before, you can't use an attruibute, and now, you can't change attribute, it's 2 differents permissions.

In your video, you only check forum permissions, or, change attribute needs a moderative permissions:

![capture3](https://user-images.githubusercontent.com/6375756/44311950-9a3d7e80-a3f0-11e8-8e78-da2de32fb5d7.PNG)
