### ISSUE TITLE
Quick Title Edition - Undefined offset: -1

### ISSUE THREAD

**Issue by melvingb** [ErnadoO/qte#5]
Hi @ErnadoO,

Recently I appeared this error do not select an attribute

[phpBB Debug] PHP Notice: in file [ROOT]/ext/ernadoo/qte/qte.php on line 126: Undefined offset: -1
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 2423: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3925)

**Comment by ErnadoO** [comment]
Hello !

This issue was resolved yesterday, can you try again ?

**Comment by melvingb** [comment]
No, I trying and the error is the same, I uploaded the new files and deactive and active the extension.

**Comment by ErnadoO** [comment]
But there are nothing Line 126: https://github.com/ErnadoO/qte/blob/master/qte.php#L126.

And you need to desactive extension BEFORE upload the new files

**Comment by melvingb** [comment]
[phpBB Debug] PHP Notice: in file [ROOT]/ext/ernadoo/qte/qte.php on line 127: Undefined offset: -1

**Comment by melvingb** [comment]
No, the error is the same
![3970803138](https://cloud.githubusercontent.com/assets/512772/16527719/acee9848-3f75-11e6-9f9f-ee7ecbd4fb1f.png)
