### ISSUE TITLE
Undefined index: topic_attr_id

### ISSUE THREAD

**Issue by melvingb** [ErnadoO/qte#6]
Hi @ErnadoO, I tested the extension and works great but recently appearing this issue

[phpBB Debug] PHP Notice: in file [ROOT]/ext/ernadoo/qte/event/main_listener.php on line 148: Undefined index: topic_attr_id
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 2423: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3925)

Note that in this forum I have no active the attributes. 

PS: Sorry for the inconvenience...

**Comment by ErnadoO** [comment]
Hello

Can i have more informations about this issue ?

Posting ? Edit ? Which attribute was selected ? Remove attribute ? etc...

Thanks :)

**Comment by melvingb** [comment]
@ErnadoO, 

The error I appeared to post a message, in the message do not have selected any attribute.

Regards...

Any other information want you needed? :)

**Comment by ErnadoO** [comment]
Thanks, i found the error :D

I will push a fix tonight or tomorrow ;)
